[supervisord]
nodaemon=true
pidfile=/supervisord.pid
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

[program:nginx_logger]
command=/usr/local/bin/nginx_logger.sh
autorestart=true
stdout_logfile=/var/log/nginx_logger_stdout.log
stderr_logfile=/var/log/nginx_logger_stderr.log
user=nginx
