
upstream redblue {
    least_conn;
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
}

server {
    listen 8081;
    server_name localhost;

    location / {
        root /var/www/hostnamematvey.zapto.org/html;
        index red_page.html;
    }
}

server {
    listen 8082;
    server_name localhost;

    location / {
        root /var/www/hostnamematvey.zapto.org/html;
        index blue_page.html;
    }
}

server {
    listen 80;
    server_name hostnamematvey.zapto.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hostnamematvey.zapto.org;

    ssl_certificate /etc/letsencrypt/live/hostnamematvey.zapto.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hostnamematvey.zapto.org/privkey.pem;
    include default.d/ssl-params.conf;

    include default.d/security-headers.conf;
    
    access_log /var/log/nginx/hostnamematvey.access.log main;
    error_log  /var/log/nginx/hostnamematvey.error.log warn;

    root /var/www/hostnamematvey.zapto.org/html;
    index index.html index.htm;
    
    include default.d/locations-static.conf;
    include default.d/locations-special.conf;
    include default.d/php.conf;
    include default.d/proxy-redblue.conf;

    include default.d/cpu.conf;
}
