===== /etc/nginx/default.d/php.conf =====

location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass unix:/run/php-fpm/www.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}


===== /etc/nginx/default.d/ssl-params.conf =====

ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;

===== /etc/nginx/default.d/locations-static.conf =====

location / {
    try_files $uri $uri/ =404;
}

location /secondpage {
    try_files /secondpage.html =404;
}

location /image1 {
    try_files /images/image1.jpeg =404;
}

location /image2 {
    try_files /images/image2.png =404;
}

location ~* /(.+)\.(jpg|jpeg)$ {
    try_files /images/$uri =404;
    image_filter rotate 180;
    error_page 415 = @unsupported;
}

location @unsupported {
    return 415 "unsupported image or process error";
}

===== /etc/nginx/default.d/locations-special.conf =====

location /music {
    alias /var/www/hostnamematvey.zapto.org/html/music/ambient-electronic-minimal_flare-11132.mp3;
    add_header Content-Type audio/mpeg;
    add_header Content-Disposition "attachment; filename=ambient-electronic-minimal_flare-11132.mp3";
}

location /secondserver {
    return 301 http://google.com;
}


===== /etc/nginx/default.d/proxy-redblue.conf =====

location /red_blue {
    proxy_pass http://redblue/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

===== /etc/nginx/default.d/security-headers.conf =====

add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options DENY;
add_header X-XSS-Protection "1; mode=block";
add_header Referrer-Policy "no-referrer-when-downgrade";

===== /etc/nginx/default.d/cpu.conf =====

location = /cpu {
    default_type text/html;
    alias /var/www/hostnamematvey.zapto.org/html/cpu_load.html;
}

location = /cpu_data {
    default_type text/plain;
    alias /var/www/hostnamematvey.zapto.org/html/cpu_load.txt;
}
