version: '3.8'

services:
  nginx:
    image: no-alpline-nginx
    container_name: my-nginx-container / matveysviadysh/apache-unroot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_apache_net
    volumes:
      - /home/ec2-user/nginx-logs:/var/log/nginx 
    depends_on:
      - apache

  apache:
    image: matveysviadysh/php-anrut
    container_name: apache_info
    ports:
      - "8080:80"
    networks:
      - nginx_apache_net

networks:
  nginx_apache_net:
    driver: bridge

#volumes:
#  ec2-user_nginx-logs:

