
[Interface]
Address = 10.1.0.1/24
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 51820
PrivateKey = eIVRAg46E76oaBT05oHmzs+yQPJx7QPgaDndJjJ4wEs=

[Peer]
PublicKey = LPcPN5lj3Li5m9RaUScQHYIpzlbX4UR1oByqbD1p31Q=
AllowedIPs = 10.1.0.2/32
Endpoint = 107.20.196.11:62705

[Peer]
PublicKey = 4ziQ2nn1QGkKaWG5ev1wpTPyxL5i3KKJtHKl8xuLPls=
AllowedIPs = 10.1.0.3/32
Endpoint = 93.84.120.226:58972
