[Interface]
Address = 10.1.0.2/24
PrivateKey = OPUSuzyMGem0WOjlZfv8FaWWBbD/SuvpeUYw/uczh2g=


[Peer]
PublicKey = HtZOJVsqrjjc5nKNN2tPD+UM9RpZscXNaKOsPssCDjM=
Endpoint = 44.199.155.137:51820
AllowedIPs = 10.1.0.1/32,10.1.0.3/32
PersistentKeepalive = 25
