- name: Install Docker on Amazon Linux
  become: yes
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "Amazon"
  yum:
    name: docker
    state: present


- name: Install Docker on Ubuntu
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  apt:
    name: docker.io
    state: present
    update_cache: yes


- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes


- name: Install Docker Compose plugin
  become: yes
  shell: |
    mkdir -p ~/.docker/cli-plugins/
    curl -SL https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-`uname -s`-`uname -m` -o ~/.docker/cli-plugins/docker-compose
    chmod +x ~/.docker/cli-plugins/docker-compose
  args:
    creates: ~/.docker/cli-plugins/docker-compose


- name: Start and enable Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes


- name: Build nginx image
  become: yes
  shell: docker build -t my-test-nginx .
  args:
    chdir: /opt/docker_apache/docker_apache/nginx


- name: Build apache image
  become: yes
  shell: docker build -t my-test-apache .
  args:
    chdir: /opt/docker_apache/docker_apache/apache

- name: Remove existing my-nginx-container if exists
  become: yes
  shell: docker rm -f my-nginx-container || true

- name: Remove existing apache_info container if exists
  become: yes
  shell: docker rm -f apache_info || true

- name: Restart docker compose services
  become: yes
  shell: |
    docker compose down
    docker compose up -d
  args:
    chdir: /opt/docker_apache/docker_apache/
