upstream redblue {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
}

server {
    listen 8081;
    server_name localhost;
    root /usr/share/nginx/html;
    
    location / {
        try_files /red_page.html =404;
    }
}

server {
    listen 8082;
    server_name localhost; 
    root /usr/share/nginx/html;
    
    location / {
        try_files /blue_page.html =404;
    }
}

server {
    listen 80;
    server_name nginxdocker123.ddns.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nginxdocker123.ddns.net;

    ssl_certificate /etc/letsencrypt/live/nginxdocker123.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nginxdocker123.ddns.net/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /red_blue {
        proxy_pass http://redblue;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Cache-Control no-store;
    }

    location /php_info/ {
        proxy_pass http://apache_info:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }



    location /second_page {
        try_files /second_page.html =404;
    }

    location /redirect {
        return 301 https://google.com;
    }

    location /img_png {
        try_files /tree.png =404;
    }

    location /img_jpeg {
        try_files /bimbim.jpeg =404;
    }

    location ~* /(.+)\.(jpg|jpeg)$ {
        try_files /$uri =404;
        image_filter rotate 180;
        error_page 415 = @unsupported;
    }

    location /music {
        alias /usr/share/nginx/html/music.mp3;
        add_header Content-Type application/octet-stream;
        add_header Content-Disposition "attachment; filename=music.mp3";
    }

    location = /cpu {
        default_type text/html;
        alias /usr/share/nginx/html/cpu_load.html;
    }

    location = /cpu_data {
        default_type text/plain;
        alias /usr/share/nginx/html/cpu_load.txt;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
}
